/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_settings_TestAudioCalibrationLib */

#ifndef _Included_com_android_settings_TestAudioCalibrationLib
#define _Included_com_android_settings_TestAudioCalibrationLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_settings_TestAudioCalibrationLib
 * Method:    tfa9890reCalibration
 * Signature: (FF)[I
 */
JNIEXPORT jintArray JNICALL Java_com_android_settings_TestAudioCalibrationLib_tfa9890reCalibration
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_android_settings_TestAudioCalibrationLib
 * Method:    goBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_settings_TestAudioCalibrationLib_goBack
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
